[versions]
kotlin = "2.2.21"
kotlinDSL = "6.4.2"
kotlinx-coroutines = "1.10.2"

kotlinxSerialization = "1.8.1"
fastutil = "8.5.18"

lwjgl = "3.3.6"
glWrapper = "1.1.0"
kmogus = "1.1-SNAPSHOT"

commons-compress = "1.28.0"
zstd-jni = "1.5.7-4"
protobufPlugin = "0.10.0"
grpcJava = "1.76.0"
protobuf = "3.25.8"

jarOptimizer = "1.2.2"

caelum = "1.0-SNAPSHOT"

[plugins]
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jarOptimizer = { id = "dev.luna5ama.jar-optimizer", version.ref = "jarOptimizer" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinDSLGradlePlugin = { module = "org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin", version.ref = "kotlinDSL" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

glWrapper-core = { module = "dev.luna5ama:gl-wrapper-core", version.ref = "glWrapper" }
glWrapper-lwjgl3 = { module = "dev.luna5ama:gl-wrapper-lwjgl-3", version.ref = "glWrapper" }

kmogus-core = { module = "dev.luna5ama:kmogus-core", version.ref = "kmogus" }

commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd-jni" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpcJava" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpcJava" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }

caelum-core = { module = "net.echonolix:caelum-core", version.ref = "caelum" }
caelum-vulkan = { module = "net.echonolix:caelum-vulkan", version.ref = "caelum" }
caelum-glfw-vulkan = { module = "net.echonolix:caelum-glfw-vulkan", version.ref = "caelum" }

[bundles]
glWrapper = ["glWrapper-core", "glWrapper-lwjgl3"]
